movie/config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :films do
    member do
      post :join
      post :quit
    end

    resources :reviews
  end

  namespace :account do
    resources :films
    resources :reviews
  end

  root 'films#index'
end

movie/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

movie/app/models/film.rb
class Film < ApplicationRecord
  validates :title, presence: true
  belongs_to :user
  has_many :reviews
  has_many :film_relationships
  has_many :members, :through => :film_relationships, :source => :user
end

movie/app/models/film_relationship.rb
class FilmRelationship < ApplicationRecord
  belongs_to :user
  belongs_to :film
end

movie/app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :film
  validates :content, presence: true
  scope :recent, -> {order("created_at DESC")}
end

movie/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :films
  has_many :reviews
  has_many :film_relationships
  has_many :marked_films, :through => :film_relationships, :source => :film

  def is_member_of?(film)
    marked_films.include?(film)
  end

  def join!(film)
    marked_films << film
  end

  def quit!(film)
    marked_films.delete(film)
  end

end

movie/app/controllers/account/films_controller.rb
class Account::FilmsController < ApplicationController
  before_action :authenticate_user!

  def index
    @films = current_user.marked_films
  end
end

movie/app/controllers/account/reviews_controller.rb
class Account::ReviewsController < ApplicationController
  before_action :authenticate_user!

  def index
    @reviews = current_user.reviews
  end

end

movie/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

movie/app/controllers/films_controller.rb
class FilmsController < ApplicationController

  before_action :authenticate_user!, only: [:new, :create, :edit, :destoy, :update, :join, :quit]
  before_action :find_film_and_check_perission, only: [:edit, :update, :destroy]

  def index
    @films = Film.all
  end

  def new
    @film = Film.new
  end

  def show
    @film = Film.find(params[:id])
    @reviews = @film.reviews.recent.paginate(:page => params[:page], :per_page => 5)
  end

  def edit
  end

  def create
    @film = Film.new(film_params)
    @film.user = current_user
    if @film.save
      current_user.join!(@film)
      redirect_to films_path
    else
      render :new
    end
  end

  def update
    if @film.update(film_params)
      redirect_to films_path, notice: "Update Success"
    else
      render :edit
    end
  end

  def destroy
    @film.destroy
    redirect_to films_path, alert: "Film Deleted"
  end

  def join
    @film = Film.find(params[:id])

    if !current_user.is_member_of?(@film)
      current_user.join!(@film)
      flash[:notice] = "Successfully marked"
    else
      flash[:warning] = "You have already marked it."
    end

    redirect_to film_path(@film)
  end

  def quit
    @film = Film.find(params[:id])

    if current_user.is_member_of?(@film)
      current_user.quit!(@film)
      flash[:alert] = "Successfully unmarked"
    else
      flash[:warning] = "Unmark failed"
    end

    redirect_to film_path(@film)
  end

  private

  def find_film_and_check_perission
    @film = Film.find(params[:id])

    if current_user != @film.user
      redirect_to root_path, alert: "You have no permission"
    end
  end

  def film_params
    params.require(:film).permit(:title, :description)
  end
end

movie/app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  before_action :authenticate_user! , only: [:new, :create]

  def new
    @film = Film.find(params[:film_id])
    @review = Review.new
  end

  def create
    @film = Film.find(params[:film_id])
    @review = Review.new(review_params)
    @review.film = @film
    @review.user = current_user

    if @review.save
      redirect_to film_path(@film)
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:content)
  end
end

movie/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    flash[:notice] = "Morning!"
  end
end

movie/app/helpers/account/films_helper.rb
module Account::FilmsHelper
end

movie/app/helpers/account/reviews_helper.rb
module Account::ReviewsHelper
end

movie/app/helpers/application_helper.rb
module ApplicationHelper
end

movie/app/helpers/films_helper.rb
module FilmsHelper
  def render_film_description(film)
    simple_format(film.description)
  end
end

movie/app/helpers/flashes_helper.rb
module FlashesHelper
  FLASH_CLASS = { alert: "danger", notice: "success", warning:"warning" }.freeze

  def flash_class(key)
    FLASH_CLASS.fetch key.to_sym, key
  end

  def user_facing_flashes
    flash.to_hash.slice "alert", "notice", "warning"
  end
end

movie/app/helpers/reviews_helper.rb
module ReviewsHelper
end

movie/app/helpers/welcome_helper.rb
module WelcomeHelper
end

movie/app/views/common/_flashes.html.erb
<% if flash.any? %>
  <% user_facing_flashes.each do |key, value| %>
    <div class="alert alert-dismissable alert-<%= flash_class(key) %>">
      <button class="close" data-dismiss="alert">×</button>
      <%= value %>
    </div>
  <% end %>
<% end %>

movie/app/views/common/_footer.html.erb
<footer class="container" style="margin-top: 100px;">
    <p class="text-center">Copyright ©2017 Movie Reviewer
        <br>Design by
        <a href="http://qiushi-li-blog.logdown.com/" target=_new>Qiushi</a>
    </p>
</footer>

movie/app/views/common/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <a class="navbar-brand" href="/">Movie Reviewer</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <li>
                  <% if !current_user %>
                    <li><%= link_to("Sign Up", new_user_registration_path ) %></li>
                    <li><%= link_to(content_tag(:i, "Sign In", class: 'fa fa-sign-in'), new_user_session_path ) %></li>
                  <% else %>
                    <li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        Hi!, <%= current_user.email %>
                        <b class="caret"></b>
                      </a>
                        <ul class="dropdown-menu">
                          <li><%= link_to("My Movies", account_films_path) %></li>
                          <li class="divider"></li>
                          <li><%= link_to("My Reviews", account_reviews_path)%></li>
                          <li class="divider"></li>
                          <li><%= link_to(content_tag(:i, "Sign out", class: 'fa fa-sign-out'), destroy_user_session_path, method: :delete )%></li>
                        </ul>
                    </li>
                  <% end %>
                </li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>

movie/app/views/films/_film_item.html.erb
<tr>
  <th scope="row"><%= film.id %></th>
  <td><%= link_to(film.title, film_path(film)) %></td>
  <td><%= render_film_description(film) %></td>
  <td><%= film.user.email%></td>
  <td>
    <% if current_user && current_user == film.user %>
      <%= link_to("Edit", edit_film_path(film), class: "btn btn-sm btn-default")%>
      <%= link_to("Delete", film_path(film),    class: "btn btn-sm btn-default",
                  method: :delete, data: { confirm: "Are you sure?" } )%>
    <% end %>
  </td>
</tr>

movie/app/views/films/_form.html.erb
<%= simple_form_for @film do |f| %>
  <div class="form-film">
    <%= f.input :title, input_html: { class: "form-control"} %>
    <%= f.input :description, input_html: { class: "form-control"} %>
  </div>
  <%= f.submit "Submit", class: "btn btn-primary", data: { disable_with: "Submiting..." } %>
<% end %>

movie/app/views/films/edit.html.erb
<div class="col-md-4 col-md-offset-4">
  <h2>Edit Movie</h2>

  <hr>
  <%= render "form" %>

</div>

movie/app/views/films/index.html.erb
<div class="col-md-12">
  <div class="film">
    <%= link_to("Add a film", new_film_path, class: "btn btn-primary pull-right")%>
  </div>
  <br>
  <table class="table table-striped table-inverse">
    <thead>
      <tr>
        <td>#</td>
        <td>Movie</td>
        <td>Main Cast</td>
        <td>Creator</td>
      </tr>
    </thead>
    <tbody>
      <%= render :partial => "film_item", :collection => @films, :as => :film %>
    </tbody>
  </table>
</div>

movie/app/views/films/new.html.erb
<div class="col-md-4 col-md-offset-4">
  <h2>Add Movie</h2>

  <hr>

  <%= render "form" %>

</div>

movie/app/views/films/show.html.erb
<div class="col-md-12">
  <div class="film">

    <span class="pull-right">
      <% if current_user && current_user.is_member_of?(@film)%>
        <label class="label label-success"> Movie Marked </label>
              <%= link_to("Unmark It", quit_film_path(@film), :method => :post, class: "btn btn-default") %>
      <% else %>
        <label class="label label-warning"> Movie Unmarked </label>
              <%= link_to("Mark It",   join_film_path(@film), :method => :post, class: "btn btn-default") %>
      <% end %>
    </span>

    <%= link_to("Write a Review", new_film_review_path(@film), class: "btn btn-default pull-right") %>

    <% if current_user && current_user == @film.user %>
    <%= link_to("Edit", edit_film_path(@film), class: "btn btn-primary pull-right")%>
    <% end %>

  </div>

  <h2><%= @film.title%></h2>
  <p><%= @film.description %></p>

  <table class="table">
    <thead>
      <tr>
        <th>Review</th>
        <th>Creator</th>
        <th>Update Time</th>
      </tr>
    </thead>
    <tbody>
      <% @reviews.each do |review| %>
        <tr>
          <td><%= review.content %></td>
          <td><%= review.user.email %></td>
          <td><%= review.created_at %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

    <div class="text-center">
      <%= will_paginate @reviews %>
    </div>

</div>

movie/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Movie Reviewer</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
      <%= render "common/navbar" %>
      <%= render "common/flashes" %>
      <%= yield %>
    </div>
      <%= render "common/footer" %>
  </body>
</html>

movie/app/views/reviews/new.html.erb
<h2 class="text-center">Add Review</h2>

<div class="col-md-4 col-md-offset-4">
  <%= simple_form_for [@film,@review] do |f| %>
    <div class="form-group">
      <%= f.input :content, input_html: { class: "form-control"} %>
    </div>
    <div class="form-actions">
      <%= f.submit "Submit", disable_with: "Submitting...", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

movie/app/views/welcome/index.html.erb
<h1> Hello World! </h1>